# Zadanie domowe -- interpolacja dwusześcienna

Interpolacja dwusześcienna, to podobnie jak w przypadku interpolacji dwuliniowej, rozszerzenie idei interpolacji jednowymiarowej na dwuwymiarową siatkę.
W trakcie jej obliczania wykorzystywane jest 16 pikseli z otoczenia (dla dwuliniowej 4).
Skutkuje to zwykle lepszymi wynikami - obraz wyjściowy jest bardziej gładki i z mniejszą liczbą artefaktów.
Ceną jest znaczny wzrost złożoności obliczeniowej (zostało to zaobserwowane podczas ćwiczenia).

Interpolacja dana jest wzorem:
\begin{equation}
I(i,j) = \sum_{i=0}^{3} \sum_{j=0}^{3} a_{ij} x^i y^j
\end{equation}

Zadanie sprowadza się zatem do wyznaczenia 16 współczynników $a_{ij}$.
W tym celu wykorzystuje się, oprócz wartość w~puntach $A$ (0,0), $B$ (1 0), $C$ (1,1), $D$ (0,1) (por. rysunek dotyczący interpolacji dwuliniowej), także pochodne cząstkowe $A_x$, $A_y$, $A_{xy}$.
Pozwala to rozwiązać układ 16-tu równań.

Jeśli zgrupujemy parametry $a_{ij}$:
\begin{equation}
a = [ a_{00}~a_{10}~a_{20}~a_{30}~a_{01}~a_{11}~a_{21}~a_{31}~a_{02}~a_{12}~a_{22}~a_{32}~a_{03}~a_{13}~a_{23}~a_{33}]
\end{equation}

i przyjmiemy:
\begin{equation}
x = [A~B~D~C~A_x~B_x~D_x~C_x~A_y~B_y~D_y~C_y~A_{xy}~B_{xy}~D_{xy}~C_{xy}]^T
\end{equation}

To zagadnienie można opisać w postaci równania liniowego:
\begin{equation}
Aa = x
\end{equation}
gdzie macierz $A^{-1}$ dana jest wzorem:

\begin{equation}
A^{-1} =
\begin{bmatrix}
1& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0& 0 \\
0&  0&  0&  0&  1&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0 \\
-3&  3&  0&  0& -2& -1&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0 \\
2& -2&  0&  0&  1&  1&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0&  1&  0&  0&  0&  0&  0&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  0&  1&  0&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0& -3&  3&  0&  0& -2& -1&  0&  0 \\
0&  0&  0&  0&  0&  0&  0&  0&  2& -2&  0&  0&  1&  1&  0&  0 \\
-3&  0&  3&  0&  0&  0&  0&  0& -2&  0& -1&  0&  0&  0&  0&  0 \\
0&  0&  0&  0& -3&  0&  3&  0&  0&  0&  0&  0& -2&  0& -1&  0 \\
9& -9& -9&  9&  6&  3& -6& -3&  6& -6&  3& -3&  4&  2&  2&  1 \\
-6&  6&  6& -6& -3& -3&  3&  3& -4&  4& -2&  2& -2& -2& -1& -1 \\
2&  0& -2&  0&  0&  0&  0&  0&  1&  0&  1&  0&  0&  0&  0&  0 \\
0&  0&  0&  0&  2&  0& -2&  0&  0&  0&  0&  0&  1&  0&  1&  0 \\
-6&  6&  6& -6& -4& -2&  4&  2& -3&  3& -3&  3& -2& -1& -2& -1 \\
4& -4& -4&  4&  2&  2& -2& -2&  2& -2&  2& -2&  1&  1&  1&  1 \\
\end{bmatrix}
\end{equation}

Potrzebne w rozważaniach pochodne cząstkowe obliczane są wg. następującego przybliżenia (przykład dla punktu A):
\begin{equation}
A_x = \frac{I(i+1,j) - I(i-1,j)}{2}
\end{equation}
\begin{equation}
A_y = \frac{I(i,j+1) - I(i,j-1)}{2}
\end{equation}
\begin{equation}
A_{xy} = \frac{I(i+1,j+1) - I(i-1,j) - I(i,j-1) + I(i,j)}{4}
\end{equation}

## Zadanie

Wykorzystując podane informacje zaimplementuj interpolację dwusześcienną.
Uwagi:
- macierz $A^{-1}$ dostępna jest w pliku *a_invert.py*
- trzeba się zastanowić nad potencjalnym wykraczaniem poza zakres obrazka (jak zwykle).

Ponadto dokonaj porównania liczby operacji arytmetycznych i dostępów do pamięci koniecznych przy realizacji obu metod interpolacji: dwuliniowej i dwusześciennej.

In [12]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from math import floor

if not os.path.exists("ainvert.py") :
    !wget https://raw.githubusercontent.com/vision-agh/poc_sw/master/05_Resolution/ainvert.py --no-check-certificate

parrot = cv2.imread('parrot.bmp')           # Read image
parrot = cv2.cvtColor(parrot, cv2.COLOR_BGR2GRAY) # Convert to RGB

import ainvert

In [9]:
print(ainvert.A_invert)

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [-3  3  0  0 -2 -1  0  0  0  0  0  0  0  0  0  0]
 [ 2 -2  0  0  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0 -3  3  0  0 -2 -1  0  0]
 [ 0  0  0  0  0  0  0  0  2 -2  0  0  1  1  0  0]
 [-3  0  3  0  0  0  0  0 -2  0 -1  0  0  0  0  0]
 [ 0  0  0  0 -3  0  3  0  0  0  0  0 -2  0 -1  0]
 [ 9 -9 -9  9  6  3 -6 -3  6 -6  3 -3  4  2  2  1]
 [-6  6  6 -6 -3 -3  3  3 -4  4 -2  2 -2 -2 -1 -1]
 [ 2  0 -2  0  0  0  0  0  1  0  1  0  0  0  0  0]
 [ 0  0  0  0  2  0 -2  0  0  0  0  0  1  0  1  0]
 [-6  6  6 -6 -4 -2  4  2 -3  3 -3  3 -2 -1 -2 -1]
 [ 4 -4 -4  4  2  2 -2 -2  2 -2  2 -2  1  1  1  1]]


In [30]:
def cubic_interpolate(image, scale):
    scale_width, scale_height = scale
    height, width = image.shape
    
    new_width, new_height = round(scale_width*width), round(scale_height*height)
    
    new_image = np.zeros((new_height, new_width), dtype='uint8')
    
    for i in range(new_width):
        for j in range(new_height):
            i1 = floor(i/scale_width)
            j1 = floor(j/scale_height)
            
            i2 = i1 + 1 if i1 < width - 1 else i1
            j2 = j1 + 1 if j1 < height - 1 else j1
            
            A = image[j1, i1]
            B = image[j1, i2]
            C = image[j2, i1]
            D = image[j2, i2]
            
            indices = [[None]*4]*4
            values = [[None]*4]*4
            
            
            #A
            pre_i = i1 - 1 if i1 > 0 else i1
            post_i = i1 + 1 if i1 < width - 1 else i1
            A_x = (image[j1, post_i] - image[j1, pre_i])/2
            pre_j = j1 - 1 if j1 > 0 else j1
            post_j = j1 + 1 if j1 < height - 1 else j1
            A_y = (image[post_j, i1] - image[pre_j, i1])/2
            A_xy =  (image[post_j, post_i] -image[j1, pre_i] - image[pre_j, i1] + image[j1, i1])/4
            
            
            #B
            pre_i = i2 - 1 if i2 > 0 else i2
            post_i = i2 + 1 if i2 < width - 1 else i2
            B_x = (image[j1, post_i] - image[j1, pre_i])/2
            
            pre_j = j1 - 1 if j1 > 0 else j1
            post_j = j1 + 1 if j1 < height - 1 else j1
            B_y = (image[post_j, i2] - image[pre_j, i2])/2
            
            B_xy =  (image[post_j, post_i] -image[j1, pre_i] - image[pre_j, i1] + image[j1, i2])/4
            
            
            #C
            pre_i = i1 - 1 if i1 > 0 else i1
            post_i = i1 + 1 if i1 < width - 1 else i1
            C_x = (image[j2, post_i] - image[j2, pre_i])/2
            
            pre_j = j2 - 1 if j2 > 0 else j2
            post_j = j2 + 1 if j2 < height - 1 else j2
            C_y = (image[post_j, i1] - image[pre_j, i1])/2
            
            C_xy =  (image[post_j, post_i] -image[j1, pre_i] - image[pre_j, i1] + image[j2, i1])/4
            
            
            pre_i = i2 - 1 if i2 > 0 else i2
            post_i = i2 + 1 if i2 < width - 1 else i2
            D_x = (image[j2, post_i] - image[j2, pre_i])/2
            
            pre_j = j2 - 1 if j2 > 0 else j2
            post_j = j2 + 1 if j2 < height - 1 else j2
            D_y = (image[post_j, i2] - image[pre_j, i2])/2
            
            D_xy =  (image[post_j, post_i] -image[j2, pre_i] - image[pre_j, i2] + image[j2, i2])/4
            
            
            x = np.array([[A, B, D, C, A_x, B_x, D_x, C_x, A_y, B_y, D_y, C_y, A_xy, B_xy, D_xy, C_xy]]).T
            
            a = ainvert.A_invert @ x
            
            dist_i = i/scale_width - i1
            dist_j = j/scale_height - j1
            
            x_pow = np.array([[1, dist_j, dist_j**2, dist_j**3]])
            y_pow = np.array([[1, dist_i, dist_i**2, dist_i**3]])
            
            image[j, i] = x_pow @ a.reshape(4, 4).T @ y_pow.T
            
    
    return new_image

In [31]:
cubic_interpolate(parrot, (1, 1))

<ipython-input-30-9f701ca9566a>:29: RuntimeWarning: overflow encountered in ubyte_scalars
  A_x = (image[j1, post_i] - image[j1, pre_i])/2
<ipython-input-30-9f701ca9566a>:33: RuntimeWarning: overflow encountered in ubyte_scalars
  A_xy =  (image[post_j, post_i] -image[j1, pre_i] - image[pre_j, i1] + image[j1, i1])/4
<ipython-input-30-9f701ca9566a>:43: RuntimeWarning: overflow encountered in ubyte_scalars
  B_y = (image[post_j, i2] - image[pre_j, i2])/2
<ipython-input-30-9f701ca9566a>:45: RuntimeWarning: overflow encountered in ubyte_scalars
  B_xy =  (image[post_j, post_i] -image[j1, pre_i] - image[pre_j, i1] + image[j1, i2])/4
<ipython-input-30-9f701ca9566a>:51: RuntimeWarning: overflow encountered in ubyte_scalars
  C_x = (image[j2, post_i] - image[j2, pre_i])/2
<ipython-input-30-9f701ca9566a>:55: RuntimeWarning: overflow encountered in ubyte_scalars
  C_y = (image[post_j, i1] - image[pre_j, i1])/2
<ipython-input-30-9f701ca9566a>:57: RuntimeWarning: overflow encountered in ubyte_scal

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)